//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

pub(crate) mod r#multisig;
pub(crate) mod r#proposal;
pub(crate) mod r#vault_transaction;

pub use self::r#multisig::*;
pub use self::r#proposal::*;
pub use self::r#vault_transaction::*;
