import { writeFileSync, mkdirSync } from "node:fs";
import {
  createFromRoot,
  resolverValueNode,
  argumentValueNode,
  setInstructionAccountDefaultValuesVisitor,
} from "codama";
import { rootNodeFromAnchor } from "@codama/nodes-from-anchor";
import { renderVisitor } from "@codama/renderers-js";
import IDL from "./cow_settlement.json" with {type: 'json'};

const codama = createFromRoot(rootNodeFromAnchor(IDL));

// order_pda seed generation requires hashing the input intent in `createOrder`
// so we use codama's `resolverValueNode` to inject custom code for this.
codama.update(
  setInstructionAccountDefaultValuesVisitor([
    {
      instruction: "createOrder",
      account: "orderPda",
      defaultValue: resolverValueNode("resolveOrderPda", {
        dependsOn: [argumentValueNode("intent")],
      }),
    },
  ]),
);

codama.accept(
  renderVisitor("./client/js", {
    // resolveOrderPda hashes with crypto.subtle.digest, which is async, so
    // codama must await it and only wire it into the *Async instruction
    // builder rather than the sync one.
    asyncResolvers: ["resolveOrderPda"],
  }),
);

// codama inlines each PDA's const seeds into the function that derives it and
// exports no constant for them, so resolveOrderPda — which builds the order PDA
// seeds by hand — has nothing to import. Emit SETTLEMENT_SEED here, read off the
// state PDA's sole const seed, so the version-dependent bytes still have exactly
// one source (the IDL) and follow it across version bumps. Written after the
// render because renderVisitor wipes its output directory first.
const settlementSeed = IDL.instructions
  .find((instruction) => instruction.name === "initialize")
  .accounts.find((account) => account.name === "state_pda").pda.seeds[0].value;

mkdirSync("./client/js/src/generated", { recursive: true });

writeFileSync(
  "./client/js/src/generated/settlementSeed.ts",
  `/**
 * This code was AUTOGENERATED by generate.mjs (not by Codama itself, which
 * inlines PDA seeds into its derivation functions instead of exporting them).
 * Please DO NOT EDIT THIS FILE, edit generate.mjs and rerun it instead.
 */

/**
 * Prefix seed shared by every PDA this program derives: the ASCII "settlement v"
 * followed by the program's major.minor version, right-padded with spaces to a
 * fixed 19 bytes. The fixed width keeps one version's seeds from being a prefix
 * of another's. These bytes change on every minor version bump.
 */
export const SETTLEMENT_SEED: Uint8Array = new Uint8Array([
  ${settlementSeed.join(", ")},
]);
`,
);
