//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use num_derive::FromPrimitive;
use thiserror::Error;

#[derive(Clone, Debug, Eq, Error, FromPrimitive, PartialEq)]
pub enum SquadsMultisigProgramError {
    /// 6000 - Found multiple members with the same pubkey
    #[error("Found multiple members with the same pubkey")]
    DuplicateMember = 0x1770,
    /// 6001 - Members array is empty
    #[error("Members array is empty")]
    EmptyMembers = 0x1771,
    /// 6002 - Too many members, can be up to 65535
    #[error("Too many members, can be up to 65535")]
    TooManyMembers = 0x1772,
    /// 6003 - Invalid threshold, must be between 1 and number of members with Vote permission
    #[error("Invalid threshold, must be between 1 and number of members with Vote permission")]
    InvalidThreshold = 0x1773,
    /// 6004 - Attempted to perform an unauthorized action
    #[error("Attempted to perform an unauthorized action")]
    Unauthorized = 0x1774,
    /// 6005 - Provided pubkey is not a member of multisig
    #[error("Provided pubkey is not a member of multisig")]
    NotAMember = 0x1775,
    /// 6006 - TransactionMessage is malformed.
    #[error("TransactionMessage is malformed.")]
    InvalidTransactionMessage = 0x1776,
    /// 6007 - Proposal is stale
    #[error("Proposal is stale")]
    StaleProposal = 0x1777,
    /// 6008 - Invalid proposal status
    #[error("Invalid proposal status")]
    InvalidProposalStatus = 0x1778,
    /// 6009 - Invalid transaction index
    #[error("Invalid transaction index")]
    InvalidTransactionIndex = 0x1779,
    /// 6010 - Member already approved the transaction
    #[error("Member already approved the transaction")]
    AlreadyApproved = 0x177A,
    /// 6011 - Member already rejected the transaction
    #[error("Member already rejected the transaction")]
    AlreadyRejected = 0x177B,
    /// 6012 - Member already cancelled the transaction
    #[error("Member already cancelled the transaction")]
    AlreadyCancelled = 0x177C,
    /// 6013 - Wrong number of accounts provided
    #[error("Wrong number of accounts provided")]
    InvalidNumberOfAccounts = 0x177D,
    /// 6014 - Invalid account provided
    #[error("Invalid account provided")]
    InvalidAccount = 0x177E,
    /// 6015 - Cannot remove last member
    #[error("Cannot remove last member")]
    RemoveLastMember = 0x177F,
    /// 6016 - Members don't include any voters
    #[error("Members don't include any voters")]
    NoVoters = 0x1780,
    /// 6017 - Members don't include any proposers
    #[error("Members don't include any proposers")]
    NoProposers = 0x1781,
    /// 6018 - Members don't include any executors
    #[error("Members don't include any executors")]
    NoExecutors = 0x1782,
    /// 6019 - `stale_transaction_index` must be <= `transaction_index`
    #[error("`stale_transaction_index` must be <= `transaction_index`")]
    InvalidStaleTransactionIndex = 0x1783,
    /// 6020 - Instruction not supported for controlled multisig
    #[error("Instruction not supported for controlled multisig")]
    NotSupportedForControlled = 0x1784,
    /// 6021 - Proposal time lock has not been released
    #[error("Proposal time lock has not been released")]
    TimeLockNotReleased = 0x1785,
    /// 6022 - Config transaction must have at least one action
    #[error("Config transaction must have at least one action")]
    NoActions = 0x1786,
    /// 6023 - Missing account
    #[error("Missing account")]
    MissingAccount = 0x1787,
    /// 6024 - Invalid mint
    #[error("Invalid mint")]
    InvalidMint = 0x1788,
    /// 6025 - Invalid destination
    #[error("Invalid destination")]
    InvalidDestination = 0x1789,
    /// 6026 - Spending limit exceeded
    #[error("Spending limit exceeded")]
    SpendingLimitExceeded = 0x178A,
    /// 6027 - Decimals don't match the mint
    #[error("Decimals don't match the mint")]
    DecimalsMismatch = 0x178B,
    /// 6028 - Member has unknown permission
    #[error("Member has unknown permission")]
    UnknownPermission = 0x178C,
    /// 6029 - Account is protected, it cannot be passed into a CPI as writable
    #[error("Account is protected, it cannot be passed into a CPI as writable")]
    ProtectedAccount = 0x178D,
    /// 6030 - Time lock exceeds the maximum allowed (90 days)
    #[error("Time lock exceeds the maximum allowed (90 days)")]
    TimeLockExceedsMaxAllowed = 0x178E,
    /// 6031 - Account is not owned by Multisig program
    #[error("Account is not owned by Multisig program")]
    IllegalAccountOwner = 0x178F,
    /// 6032 - Rent reclamation is disabled for this multisig
    #[error("Rent reclamation is disabled for this multisig")]
    RentReclamationDisabled = 0x1790,
    /// 6033 - Invalid rent collector address
    #[error("Invalid rent collector address")]
    InvalidRentCollector = 0x1791,
    /// 6034 - Proposal is for another multisig
    #[error("Proposal is for another multisig")]
    ProposalForAnotherMultisig = 0x1792,
    /// 6035 - Transaction is for another multisig
    #[error("Transaction is for another multisig")]
    TransactionForAnotherMultisig = 0x1793,
    /// 6036 - Transaction doesn't match proposal
    #[error("Transaction doesn't match proposal")]
    TransactionNotMatchingProposal = 0x1794,
    /// 6037 - Transaction is not last in batch
    #[error("Transaction is not last in batch")]
    TransactionNotLastInBatch = 0x1795,
    /// 6038 - Batch is not empty
    #[error("Batch is not empty")]
    BatchNotEmpty = 0x1796,
    /// 6039 - Invalid SpendingLimit amount
    #[error("Invalid SpendingLimit amount")]
    SpendingLimitInvalidAmount = 0x1797,
    /// 6040 - Invalid Instruction Arguments
    #[error("Invalid Instruction Arguments")]
    InvalidInstructionArgs = 0x1798,
    /// 6041 - Final message buffer hash doesnt match the expected hash
    #[error("Final message buffer hash doesnt match the expected hash")]
    FinalBufferHashMismatch = 0x1799,
    /// 6042 - Final buffer size cannot exceed 4000 bytes
    #[error("Final buffer size cannot exceed 4000 bytes")]
    FinalBufferSizeExceeded = 0x179A,
    /// 6043 - Final buffer size mismatch
    #[error("Final buffer size mismatch")]
    FinalBufferSizeMismatch = 0x179B,
    /// 6044 - multisig_create has been deprecated. Use multisig_create_v2 instead.
    #[error("multisig_create has been deprecated. Use multisig_create_v2 instead.")]
    MultisigCreateDeprecated = 0x179C,
}

impl From<SquadsMultisigProgramError> for solana_program_error::ProgramError {
    fn from(e: SquadsMultisigProgramError) -> Self {
        solana_program_error::ProgramError::Custom(e as u32)
    }
}
