//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

pub(crate) mod r#proposal_approve;
pub(crate) mod r#proposal_create;
pub(crate) mod r#vault_transaction_create;

pub use self::r#proposal_approve::*;
pub use self::r#proposal_create::*;
pub use self::r#vault_transaction_create::*;
