//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;

pub const PROPOSAL_CREATE_DISCRIMINATOR: [u8; 8] = [220, 60, 73, 224, 30, 108, 79, 159];

/// Accounts.
#[derive(Debug)]
pub struct ProposalCreate {
    pub multisig: solana_address::Address,

    pub proposal: solana_address::Address,
    /// The member of the multisig that is creating the proposal.
    pub creator: solana_address::Address,
    /// The payer for the proposal account rent.
    pub rent_payer: solana_address::Address,

    pub system_program: solana_address::Address,
}

impl ProposalCreate {
    pub fn instruction(
        &self,
        args: ProposalCreateInstructionArgs,
    ) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(args, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        args: ProposalCreateInstructionArgs,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(5 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.multisig,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(self.proposal, false));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.creator,
            true,
        ));
        accounts.push(solana_instruction::AccountMeta::new(self.rent_payer, true));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.system_program,
            false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let mut data = ProposalCreateInstructionData::new().try_to_vec().unwrap();
        let mut args = args.try_to_vec().unwrap();
        data.append(&mut args);

        solana_instruction::Instruction {
            program_id: crate::SQUADS_MULTISIG_PROGRAM_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct ProposalCreateInstructionData {
    discriminator: [u8; 8],
}

impl ProposalCreateInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [220, 60, 73, 224, 30, 108, 79, 159],
        }
    }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

impl Default for ProposalCreateInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct ProposalCreateInstructionArgs {
    pub transaction_index: u64,
    pub draft: bool,
}

impl ProposalCreateInstructionArgs {
    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

/// Instruction builder for `ProposalCreate`.
///
/// ### Accounts:
///
///   0. `[]` multisig
///   1. `[writable]` proposal
///   2. `[signer]` creator
///   3. `[writable, signer]` rent_payer
///   4. `[optional]` system_program (default to `11111111111111111111111111111111`)
#[derive(Clone, Debug, Default)]
pub struct ProposalCreateBuilder {
    multisig: Option<solana_address::Address>,
    proposal: Option<solana_address::Address>,
    creator: Option<solana_address::Address>,
    rent_payer: Option<solana_address::Address>,
    system_program: Option<solana_address::Address>,
    transaction_index: Option<u64>,
    draft: Option<bool>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl ProposalCreateBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    #[inline(always)]
    pub fn multisig(&mut self, multisig: solana_address::Address) -> &mut Self {
        self.multisig = Some(multisig);
        self
    }
    #[inline(always)]
    pub fn proposal(&mut self, proposal: solana_address::Address) -> &mut Self {
        self.proposal = Some(proposal);
        self
    }
    /// The member of the multisig that is creating the proposal.
    #[inline(always)]
    pub fn creator(&mut self, creator: solana_address::Address) -> &mut Self {
        self.creator = Some(creator);
        self
    }
    /// The payer for the proposal account rent.
    #[inline(always)]
    pub fn rent_payer(&mut self, rent_payer: solana_address::Address) -> &mut Self {
        self.rent_payer = Some(rent_payer);
        self
    }
    /// `[optional account, default to '11111111111111111111111111111111']`
    #[inline(always)]
    pub fn system_program(&mut self, system_program: solana_address::Address) -> &mut Self {
        self.system_program = Some(system_program);
        self
    }
    #[inline(always)]
    pub fn transaction_index(&mut self, transaction_index: u64) -> &mut Self {
        self.transaction_index = Some(transaction_index);
        self
    }
    #[inline(always)]
    pub fn draft(&mut self, draft: bool) -> &mut Self {
        self.draft = Some(draft);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = ProposalCreate {
            multisig: self.multisig.expect("multisig is not set"),
            proposal: self.proposal.expect("proposal is not set"),
            creator: self.creator.expect("creator is not set"),
            rent_payer: self.rent_payer.expect("rent_payer is not set"),
            system_program: self
                .system_program
                .unwrap_or(solana_address::address!("11111111111111111111111111111111")),
        };
        let args = ProposalCreateInstructionArgs {
            transaction_index: self
                .transaction_index
                .clone()
                .expect("transaction_index is not set"),
            draft: self.draft.clone().expect("draft is not set"),
        };

        accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
    }
}

/// `proposal_create` CPI accounts.
pub struct ProposalCreateCpiAccounts<'a, 'b> {
    pub multisig: &'b solana_account_info::AccountInfo<'a>,

    pub proposal: &'b solana_account_info::AccountInfo<'a>,
    /// The member of the multisig that is creating the proposal.
    pub creator: &'b solana_account_info::AccountInfo<'a>,
    /// The payer for the proposal account rent.
    pub rent_payer: &'b solana_account_info::AccountInfo<'a>,

    pub system_program: &'b solana_account_info::AccountInfo<'a>,
}

/// `proposal_create` CPI instruction.
pub struct ProposalCreateCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,

    pub multisig: &'b solana_account_info::AccountInfo<'a>,

    pub proposal: &'b solana_account_info::AccountInfo<'a>,
    /// The member of the multisig that is creating the proposal.
    pub creator: &'b solana_account_info::AccountInfo<'a>,
    /// The payer for the proposal account rent.
    pub rent_payer: &'b solana_account_info::AccountInfo<'a>,

    pub system_program: &'b solana_account_info::AccountInfo<'a>,
    /// The arguments for the instruction.
    pub __args: ProposalCreateInstructionArgs,
}

impl<'a, 'b> ProposalCreateCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: ProposalCreateCpiAccounts<'a, 'b>,
        args: ProposalCreateInstructionArgs,
    ) -> Self {
        Self {
            __program: program,
            multisig: accounts.multisig,
            proposal: accounts.proposal,
            creator: accounts.creator,
            rent_payer: accounts.rent_payer,
            system_program: accounts.system_program,
            __args: args,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        let mut accounts = Vec::with_capacity(5 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.multisig.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.proposal.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.creator.key,
            true,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.rent_payer.key,
            true,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_writable: remaining_account.1,
                is_signer: remaining_account.2,
            })
        });
        let mut data = ProposalCreateInstructionData::new().try_to_vec().unwrap();
        let mut args = self.__args.try_to_vec().unwrap();
        data.append(&mut args);

        let instruction = solana_instruction::Instruction {
            program_id: crate::SQUADS_MULTISIG_PROGRAM_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(6 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.multisig.clone());
        account_infos.push(self.proposal.clone());
        account_infos.push(self.creator.clone());
        account_infos.push(self.rent_payer.clone());
        account_infos.push(self.system_program.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `ProposalCreate` via CPI.
///
/// ### Accounts:
///
///   0. `[]` multisig
///   1. `[writable]` proposal
///   2. `[signer]` creator
///   3. `[writable, signer]` rent_payer
///   4. `[]` system_program
#[derive(Clone, Debug)]
pub struct ProposalCreateCpiBuilder<'a, 'b> {
    instruction: Box<ProposalCreateCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> ProposalCreateCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(ProposalCreateCpiBuilderInstruction {
            __program: program,
            multisig: None,
            proposal: None,
            creator: None,
            rent_payer: None,
            system_program: None,
            transaction_index: None,
            draft: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    #[inline(always)]
    pub fn multisig(&mut self, multisig: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.multisig = Some(multisig);
        self
    }
    #[inline(always)]
    pub fn proposal(&mut self, proposal: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.proposal = Some(proposal);
        self
    }
    /// The member of the multisig that is creating the proposal.
    #[inline(always)]
    pub fn creator(&mut self, creator: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.creator = Some(creator);
        self
    }
    /// The payer for the proposal account rent.
    #[inline(always)]
    pub fn rent_payer(
        &mut self,
        rent_payer: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.rent_payer = Some(rent_payer);
        self
    }
    #[inline(always)]
    pub fn system_program(
        &mut self,
        system_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.system_program = Some(system_program);
        self
    }
    #[inline(always)]
    pub fn transaction_index(&mut self, transaction_index: u64) -> &mut Self {
        self.instruction.transaction_index = Some(transaction_index);
        self
    }
    #[inline(always)]
    pub fn draft(&mut self, draft: bool) -> &mut Self {
        self.instruction.draft = Some(draft);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let args = ProposalCreateInstructionArgs {
            transaction_index: self
                .instruction
                .transaction_index
                .clone()
                .expect("transaction_index is not set"),
            draft: self.instruction.draft.clone().expect("draft is not set"),
        };
        let instruction = ProposalCreateCpi {
            __program: self.instruction.__program,

            multisig: self.instruction.multisig.expect("multisig is not set"),

            proposal: self.instruction.proposal.expect("proposal is not set"),

            creator: self.instruction.creator.expect("creator is not set"),

            rent_payer: self.instruction.rent_payer.expect("rent_payer is not set"),

            system_program: self
                .instruction
                .system_program
                .expect("system_program is not set"),
            __args: args,
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct ProposalCreateCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    multisig: Option<&'b solana_account_info::AccountInfo<'a>>,
    proposal: Option<&'b solana_account_info::AccountInfo<'a>>,
    creator: Option<&'b solana_account_info::AccountInfo<'a>>,
    rent_payer: Option<&'b solana_account_info::AccountInfo<'a>>,
    system_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    transaction_index: Option<u64>,
    draft: Option<bool>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
