//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;

pub const PROPOSAL_APPROVE_DISCRIMINATOR: [u8; 8] = [144, 37, 164, 136, 188, 216, 42, 248];

/// Accounts.
#[derive(Debug)]
pub struct ProposalApprove {
    pub multisig: solana_address::Address,

    pub member: solana_address::Address,

    pub proposal: solana_address::Address,
}

impl ProposalApprove {
    pub fn instruction(
        &self,
        args: ProposalApproveInstructionArgs,
    ) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(args, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        args: ProposalApproveInstructionArgs,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(3 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.multisig,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(self.member, true));
        accounts.push(solana_instruction::AccountMeta::new(self.proposal, false));
        accounts.extend_from_slice(remaining_accounts);
        let mut data = ProposalApproveInstructionData::new().try_to_vec().unwrap();
        let mut args = args.try_to_vec().unwrap();
        data.append(&mut args);

        solana_instruction::Instruction {
            program_id: crate::SQUADS_MULTISIG_PROGRAM_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct ProposalApproveInstructionData {
    discriminator: [u8; 8],
}

impl ProposalApproveInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [144, 37, 164, 136, 188, 216, 42, 248],
        }
    }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

impl Default for ProposalApproveInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct ProposalApproveInstructionArgs {
    pub memo: Option<String>,
}

impl ProposalApproveInstructionArgs {
    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

/// Instruction builder for `ProposalApprove`.
///
/// ### Accounts:
///
///   0. `[]` multisig
///   1. `[writable, signer]` member
///   2. `[writable]` proposal
#[derive(Clone, Debug, Default)]
pub struct ProposalApproveBuilder {
    multisig: Option<solana_address::Address>,
    member: Option<solana_address::Address>,
    proposal: Option<solana_address::Address>,
    memo: Option<String>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl ProposalApproveBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    #[inline(always)]
    pub fn multisig(&mut self, multisig: solana_address::Address) -> &mut Self {
        self.multisig = Some(multisig);
        self
    }
    #[inline(always)]
    pub fn member(&mut self, member: solana_address::Address) -> &mut Self {
        self.member = Some(member);
        self
    }
    #[inline(always)]
    pub fn proposal(&mut self, proposal: solana_address::Address) -> &mut Self {
        self.proposal = Some(proposal);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn memo(&mut self, memo: String) -> &mut Self {
        self.memo = Some(memo);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = ProposalApprove {
            multisig: self.multisig.expect("multisig is not set"),
            member: self.member.expect("member is not set"),
            proposal: self.proposal.expect("proposal is not set"),
        };
        let args = ProposalApproveInstructionArgs {
            memo: self.memo.clone(),
        };

        accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
    }
}

/// `proposal_approve` CPI accounts.
pub struct ProposalApproveCpiAccounts<'a, 'b> {
    pub multisig: &'b solana_account_info::AccountInfo<'a>,

    pub member: &'b solana_account_info::AccountInfo<'a>,

    pub proposal: &'b solana_account_info::AccountInfo<'a>,
}

/// `proposal_approve` CPI instruction.
pub struct ProposalApproveCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,

    pub multisig: &'b solana_account_info::AccountInfo<'a>,

    pub member: &'b solana_account_info::AccountInfo<'a>,

    pub proposal: &'b solana_account_info::AccountInfo<'a>,
    /// The arguments for the instruction.
    pub __args: ProposalApproveInstructionArgs,
}

impl<'a, 'b> ProposalApproveCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: ProposalApproveCpiAccounts<'a, 'b>,
        args: ProposalApproveInstructionArgs,
    ) -> Self {
        Self {
            __program: program,
            multisig: accounts.multisig,
            member: accounts.member,
            proposal: accounts.proposal,
            __args: args,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        let mut accounts = Vec::with_capacity(3 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.multisig.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(*self.member.key, true));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.proposal.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_writable: remaining_account.1,
                is_signer: remaining_account.2,
            })
        });
        let mut data = ProposalApproveInstructionData::new().try_to_vec().unwrap();
        let mut args = self.__args.try_to_vec().unwrap();
        data.append(&mut args);

        let instruction = solana_instruction::Instruction {
            program_id: crate::SQUADS_MULTISIG_PROGRAM_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(4 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.multisig.clone());
        account_infos.push(self.member.clone());
        account_infos.push(self.proposal.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `ProposalApprove` via CPI.
///
/// ### Accounts:
///
///   0. `[]` multisig
///   1. `[writable, signer]` member
///   2. `[writable]` proposal
#[derive(Clone, Debug)]
pub struct ProposalApproveCpiBuilder<'a, 'b> {
    instruction: Box<ProposalApproveCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> ProposalApproveCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(ProposalApproveCpiBuilderInstruction {
            __program: program,
            multisig: None,
            member: None,
            proposal: None,
            memo: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    #[inline(always)]
    pub fn multisig(&mut self, multisig: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.multisig = Some(multisig);
        self
    }
    #[inline(always)]
    pub fn member(&mut self, member: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.member = Some(member);
        self
    }
    #[inline(always)]
    pub fn proposal(&mut self, proposal: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.proposal = Some(proposal);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn memo(&mut self, memo: String) -> &mut Self {
        self.instruction.memo = Some(memo);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let args = ProposalApproveInstructionArgs {
            memo: self.instruction.memo.clone(),
        };
        let instruction = ProposalApproveCpi {
            __program: self.instruction.__program,

            multisig: self.instruction.multisig.expect("multisig is not set"),

            member: self.instruction.member.expect("member is not set"),

            proposal: self.instruction.proposal.expect("proposal is not set"),
            __args: args,
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct ProposalApproveCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    multisig: Option<&'b solana_account_info::AccountInfo<'a>>,
    member: Option<&'b solana_account_info::AccountInfo<'a>>,
    proposal: Option<&'b solana_account_info::AccountInfo<'a>>,
    memo: Option<String>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
