//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;

pub const VAULT_TRANSACTION_CREATE_DISCRIMINATOR: [u8; 8] = [48, 250, 78, 168, 208, 226, 218, 211];

/// Accounts.
#[derive(Debug)]
pub struct VaultTransactionCreate {
    pub multisig: solana_address::Address,

    pub transaction: solana_address::Address,
    /// The member of the multisig that is creating the transaction.
    pub creator: solana_address::Address,
    /// The payer for the transaction account rent.
    pub rent_payer: solana_address::Address,

    pub system_program: solana_address::Address,
}

impl VaultTransactionCreate {
    pub fn instruction(
        &self,
        args: VaultTransactionCreateInstructionArgs,
    ) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(args, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        args: VaultTransactionCreateInstructionArgs,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(5 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(self.multisig, false));
        accounts.push(solana_instruction::AccountMeta::new(
            self.transaction,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.creator,
            true,
        ));
        accounts.push(solana_instruction::AccountMeta::new(self.rent_payer, true));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.system_program,
            false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let mut data = VaultTransactionCreateInstructionData::new()
            .try_to_vec()
            .unwrap();
        let mut args = args.try_to_vec().unwrap();
        data.append(&mut args);

        solana_instruction::Instruction {
            program_id: crate::SQUADS_MULTISIG_PROGRAM_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct VaultTransactionCreateInstructionData {
    discriminator: [u8; 8],
}

impl VaultTransactionCreateInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [48, 250, 78, 168, 208, 226, 218, 211],
        }
    }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

impl Default for VaultTransactionCreateInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct VaultTransactionCreateInstructionArgs {
    pub vault_index: u8,
    pub ephemeral_signers: u8,
    pub transaction_message: Vec<u8>,
    pub memo: Option<String>,
}

impl VaultTransactionCreateInstructionArgs {
    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

/// Instruction builder for `VaultTransactionCreate`.
///
/// ### Accounts:
///
///   0. `[writable]` multisig
///   1. `[writable]` transaction
///   2. `[signer]` creator
///   3. `[writable, signer]` rent_payer
///   4. `[optional]` system_program (default to `11111111111111111111111111111111`)
#[derive(Clone, Debug, Default)]
pub struct VaultTransactionCreateBuilder {
    multisig: Option<solana_address::Address>,
    transaction: Option<solana_address::Address>,
    creator: Option<solana_address::Address>,
    rent_payer: Option<solana_address::Address>,
    system_program: Option<solana_address::Address>,
    vault_index: Option<u8>,
    ephemeral_signers: Option<u8>,
    transaction_message: Option<Vec<u8>>,
    memo: Option<String>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl VaultTransactionCreateBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    #[inline(always)]
    pub fn multisig(&mut self, multisig: solana_address::Address) -> &mut Self {
        self.multisig = Some(multisig);
        self
    }
    #[inline(always)]
    pub fn transaction(&mut self, transaction: solana_address::Address) -> &mut Self {
        self.transaction = Some(transaction);
        self
    }
    /// The member of the multisig that is creating the transaction.
    #[inline(always)]
    pub fn creator(&mut self, creator: solana_address::Address) -> &mut Self {
        self.creator = Some(creator);
        self
    }
    /// The payer for the transaction account rent.
    #[inline(always)]
    pub fn rent_payer(&mut self, rent_payer: solana_address::Address) -> &mut Self {
        self.rent_payer = Some(rent_payer);
        self
    }
    /// `[optional account, default to '11111111111111111111111111111111']`
    #[inline(always)]
    pub fn system_program(&mut self, system_program: solana_address::Address) -> &mut Self {
        self.system_program = Some(system_program);
        self
    }
    #[inline(always)]
    pub fn vault_index(&mut self, vault_index: u8) -> &mut Self {
        self.vault_index = Some(vault_index);
        self
    }
    #[inline(always)]
    pub fn ephemeral_signers(&mut self, ephemeral_signers: u8) -> &mut Self {
        self.ephemeral_signers = Some(ephemeral_signers);
        self
    }
    #[inline(always)]
    pub fn transaction_message(&mut self, transaction_message: Vec<u8>) -> &mut Self {
        self.transaction_message = Some(transaction_message);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn memo(&mut self, memo: String) -> &mut Self {
        self.memo = Some(memo);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = VaultTransactionCreate {
            multisig: self.multisig.expect("multisig is not set"),
            transaction: self.transaction.expect("transaction is not set"),
            creator: self.creator.expect("creator is not set"),
            rent_payer: self.rent_payer.expect("rent_payer is not set"),
            system_program: self
                .system_program
                .unwrap_or(solana_address::address!("11111111111111111111111111111111")),
        };
        let args = VaultTransactionCreateInstructionArgs {
            vault_index: self.vault_index.clone().expect("vault_index is not set"),
            ephemeral_signers: self
                .ephemeral_signers
                .clone()
                .expect("ephemeral_signers is not set"),
            transaction_message: self
                .transaction_message
                .clone()
                .expect("transaction_message is not set"),
            memo: self.memo.clone(),
        };

        accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
    }
}

/// `vault_transaction_create` CPI accounts.
pub struct VaultTransactionCreateCpiAccounts<'a, 'b> {
    pub multisig: &'b solana_account_info::AccountInfo<'a>,

    pub transaction: &'b solana_account_info::AccountInfo<'a>,
    /// The member of the multisig that is creating the transaction.
    pub creator: &'b solana_account_info::AccountInfo<'a>,
    /// The payer for the transaction account rent.
    pub rent_payer: &'b solana_account_info::AccountInfo<'a>,

    pub system_program: &'b solana_account_info::AccountInfo<'a>,
}

/// `vault_transaction_create` CPI instruction.
pub struct VaultTransactionCreateCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,

    pub multisig: &'b solana_account_info::AccountInfo<'a>,

    pub transaction: &'b solana_account_info::AccountInfo<'a>,
    /// The member of the multisig that is creating the transaction.
    pub creator: &'b solana_account_info::AccountInfo<'a>,
    /// The payer for the transaction account rent.
    pub rent_payer: &'b solana_account_info::AccountInfo<'a>,

    pub system_program: &'b solana_account_info::AccountInfo<'a>,
    /// The arguments for the instruction.
    pub __args: VaultTransactionCreateInstructionArgs,
}

impl<'a, 'b> VaultTransactionCreateCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: VaultTransactionCreateCpiAccounts<'a, 'b>,
        args: VaultTransactionCreateInstructionArgs,
    ) -> Self {
        Self {
            __program: program,
            multisig: accounts.multisig,
            transaction: accounts.transaction,
            creator: accounts.creator,
            rent_payer: accounts.rent_payer,
            system_program: accounts.system_program,
            __args: args,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        let mut accounts = Vec::with_capacity(5 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(
            *self.multisig.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.transaction.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.creator.key,
            true,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.rent_payer.key,
            true,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_writable: remaining_account.1,
                is_signer: remaining_account.2,
            })
        });
        let mut data = VaultTransactionCreateInstructionData::new()
            .try_to_vec()
            .unwrap();
        let mut args = self.__args.try_to_vec().unwrap();
        data.append(&mut args);

        let instruction = solana_instruction::Instruction {
            program_id: crate::SQUADS_MULTISIG_PROGRAM_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(6 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.multisig.clone());
        account_infos.push(self.transaction.clone());
        account_infos.push(self.creator.clone());
        account_infos.push(self.rent_payer.clone());
        account_infos.push(self.system_program.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `VaultTransactionCreate` via CPI.
///
/// ### Accounts:
///
///   0. `[writable]` multisig
///   1. `[writable]` transaction
///   2. `[signer]` creator
///   3. `[writable, signer]` rent_payer
///   4. `[]` system_program
#[derive(Clone, Debug)]
pub struct VaultTransactionCreateCpiBuilder<'a, 'b> {
    instruction: Box<VaultTransactionCreateCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> VaultTransactionCreateCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(VaultTransactionCreateCpiBuilderInstruction {
            __program: program,
            multisig: None,
            transaction: None,
            creator: None,
            rent_payer: None,
            system_program: None,
            vault_index: None,
            ephemeral_signers: None,
            transaction_message: None,
            memo: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    #[inline(always)]
    pub fn multisig(&mut self, multisig: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.multisig = Some(multisig);
        self
    }
    #[inline(always)]
    pub fn transaction(
        &mut self,
        transaction: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.transaction = Some(transaction);
        self
    }
    /// The member of the multisig that is creating the transaction.
    #[inline(always)]
    pub fn creator(&mut self, creator: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.creator = Some(creator);
        self
    }
    /// The payer for the transaction account rent.
    #[inline(always)]
    pub fn rent_payer(
        &mut self,
        rent_payer: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.rent_payer = Some(rent_payer);
        self
    }
    #[inline(always)]
    pub fn system_program(
        &mut self,
        system_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.system_program = Some(system_program);
        self
    }
    #[inline(always)]
    pub fn vault_index(&mut self, vault_index: u8) -> &mut Self {
        self.instruction.vault_index = Some(vault_index);
        self
    }
    #[inline(always)]
    pub fn ephemeral_signers(&mut self, ephemeral_signers: u8) -> &mut Self {
        self.instruction.ephemeral_signers = Some(ephemeral_signers);
        self
    }
    #[inline(always)]
    pub fn transaction_message(&mut self, transaction_message: Vec<u8>) -> &mut Self {
        self.instruction.transaction_message = Some(transaction_message);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn memo(&mut self, memo: String) -> &mut Self {
        self.instruction.memo = Some(memo);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let args = VaultTransactionCreateInstructionArgs {
            vault_index: self
                .instruction
                .vault_index
                .clone()
                .expect("vault_index is not set"),
            ephemeral_signers: self
                .instruction
                .ephemeral_signers
                .clone()
                .expect("ephemeral_signers is not set"),
            transaction_message: self
                .instruction
                .transaction_message
                .clone()
                .expect("transaction_message is not set"),
            memo: self.instruction.memo.clone(),
        };
        let instruction = VaultTransactionCreateCpi {
            __program: self.instruction.__program,

            multisig: self.instruction.multisig.expect("multisig is not set"),

            transaction: self
                .instruction
                .transaction
                .expect("transaction is not set"),

            creator: self.instruction.creator.expect("creator is not set"),

            rent_payer: self.instruction.rent_payer.expect("rent_payer is not set"),

            system_program: self
                .instruction
                .system_program
                .expect("system_program is not set"),
            __args: args,
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct VaultTransactionCreateCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    multisig: Option<&'b solana_account_info::AccountInfo<'a>>,
    transaction: Option<&'b solana_account_info::AccountInfo<'a>>,
    creator: Option<&'b solana_account_info::AccountInfo<'a>>,
    rent_payer: Option<&'b solana_account_info::AccountInfo<'a>>,
    system_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    vault_index: Option<u8>,
    ephemeral_signers: Option<u8>,
    transaction_message: Option<Vec<u8>>,
    memo: Option<String>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
