//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use solana_address::{address, Address};

/// `squads_multisig_program` program ID.
pub const SQUADS_MULTISIG_PROGRAM_ID: Address =
    address!("SQDS4ep65T869zMMBKyuUq6aD6EgTu8psMjkvj52pCf");
