name: CI

on:
  push:
  pull_request:

env:
  # Bump to upgrade. Releases: https://github.com/anza-xyz/agave/releases
  SOLANA_VERSION: v3.1.14
  # Bump to upgrade. Releases: https://github.com/casey/just/releases
  JUST_VERSION: "1.51.0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Solana toolchain
        # The official Solana GitHub Action can be found at:
        # https://github.com/solana-program/actions/tree/main/install-solana
        # However, it doesn't pin dependencies to commit values and it's
        # rejected by CoW's Actions pinning policy.
        # Here we use a simplified version of the commands in the above action.
        run: |
          sh -c "$(curl -sSfL "https://release.anza.xyz/${{ env.SOLANA_VERSION }}/install")"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> "$GITHUB_PATH"

      - name: Solana version
        run: solana --version

      - name: Install just
        # Recommended in just's README, "GitHub Actions" section:
        # https://github.com/casey/just?tab=readme-ov-file#github-actions
        uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4
        with:
          just-version: ${{ env.JUST_VERSION }}

      - name: just version
        run: just --version

      - name: Build
        run: just build
